### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
ping @daddyz

**Comment by n-rodriguez** [comment]
@daddyz  Hi there! Any news?

**Comment by seuros** [comment]
A new version was released yesterday... so..

**Review by seuros — APPROVED** [review]

**Comment by n-rodriguez** [comment]
hi @seuros ! long time no see 😄 I've reduced the scope of this PR to 2 small fixes. Thank you!

**Review by seuros — APPROVED** [review]

**Pull request merged**
